### ISSUE TITLE
a path-like path

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#18]
The Build - and Terraforming Team has decidet to change the Pathblocks to a maodell like the normal path (one pixel smaller) so i doo it ;
- [x] Path block gravel
- [x] Path block grass_path
- [x] Path block coarse_dirt
- [x] Path slab top gravel
- [x] Path slab top grass_path
- [x] Path slab top coarse_dirt
- [x] Path slab bottom gravel
- [x] Path slab bottom grass_path
- [x] Path slab bottom coarse_dirt

**Comment by VoidShadow204** [comment]
we cant make the blocks one pixel smaller, because of the unloading-texture-system from MC
while placing the pathblock, i will disable the side of the other block and you get a "x-ray-window"

Sorry for this

**Comment by MCAlagaesia** [comment]
We don't need the path mix block to be one pixel shorter.

Actually, we don't really need a full block at all - we only need the slab.

Whenever we need to make a full block path, we should only use the _actual_ blocks (gravel block, coarse dirt block, path block, etc).

The path mix slab is all we really need. Perhaps we can save red sandstone blocks to use as something else. See my new issue #21.
