### ISSUE TITLE
Burnt out torch

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#2]
**Replaces:** Redstone torch
**Background information:** Burnt out torches still emit the dull glow of a redstone torch and provide dark, eerie lighting.
They may be re-lit using flint and steel, temporarily turning them into normal torches.
This  only affects torches that were originally redstone torches - A normal torch placed in the world will never burn out.

**Comment by VoidShadow204** [comment]
- Created a 32x Texture for the torch an the burned-out-torch (redstone-torch)
- created some blockstates for the torches 
- created 4 moells for the torches (on/off | wall/block)
- add and edit the particle texture (dust&fire - particle to 32x)
