### ISSUE TITLE
Sugar Cane

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#25]
Some 3D models for the Sugar Cane brings more live to the costof anny lake and river.
- [x] New 32x texture for Sugar Cane
- [x] 3D Model for Sugar Cane
- [x] leaves texture

**Comment by MCAlagaesia** [comment]
The sugarcane model is a definite improvement over vanilla!

The only thing I think needs improvement is the floating sugarcane. It's harder to see from above but is definitely noticeable when you're in the water.

![2019-06-17_17 35 39](https://user-images.githubusercontent.com/10643460/59586523-805eec00-9126-11e9-9536-19d620f34205.png)

**Comment by VoidShadow204** [comment]
Fixed it with a past update (0.7.2 "Fix for Floating Sugar-Cane")
