### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#30]
The font is everywere, annytime, you write something, or read something in the GUI.
It should look medival.
![Unbenannt](https://user-images.githubusercontent.com/47636390/59781864-0ad95400-92bd-11e9-97e7-65ff780a38c1.PNG)

**Comment by VoidShadow204** [comment]
It seems like everyone likes it. So, no more work required.

**Comment by MCAlagaesia** [comment]
I think the font size is too small for us to try anything fancy with it (like making it look medieval as you said here).

It's ended up too pixelated and wavy. How about just using the font in Faithful?

![image](https://user-images.githubusercontent.com/10643460/98643110-9952e780-2382-11eb-9a18-a5c61a856159.png)
Above: Fairth
Below: Faithful


![image](https://user-images.githubusercontent.com/10643460/98643589-52b1bd00-2383-11eb-91f3-9daf084ef9ae.png)
Left: Fairth
Right: Faithful

**Comment by MCAlagaesia** [comment]
`1` and `l` are too similar in the font.

![image](https://user-images.githubusercontent.com/10643460/113857623-14abae80-97e6-11eb-9cf2-8f970ed7211a.png)

Find the `l`.

**Comment by VoidShadow204** [comment]
I agree with you, Faithfuls Font is easier to read. I remove the old one.
