### ISSUE TITLE
Black borders on leaves when graphics are set to fast

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#34]
As seen in the image below, leaves have an undesirable black border when graphics are set to fast.

Steps to reproduce:
1. Enable [Fairth v 0.9.2](https://github.com/MCAlagaesiaNetwork/Fairth/releases/tag/v0.9.2-alpha)
1. Switch graphics from Fancy to Fast (Game Menu > Options > Video Settings > Graphics)

![image](https://user-images.githubusercontent.com/10643460/62298803-107aaa00-b4b7-11e9-888b-e4b6bd6c8cc2.png)

**Comment by MCAlagaesia** [comment]
Workaround: https://kanban.mcalagaesia.com/project/18/task/683

**Comment by Sjmarf** [comment]
Fyi, this still happens on the new leaf models.

Unfortunately, there is no way to fix this without using Fairth Fast. We could fix this in Arcaena though.
