### ISSUE TITLE
Candles

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#35]
Replaces: Sea Pickles

**Comment by VoidShadow204** [comment]
It seems like we are getting candles in 1.17 "Caves and Cliffs"
![mc_17_candles](https://user-images.githubusercontent.com/47636390/96372483-4f058e80-1167-11eb-867c-1dcf3d6edd86.PNG)

**Comment by MCAlagaesia** [comment]
Fantastic. Happy to close this issue and just use vanilla (or more accurately Faithful) candles in 1.17.
