### ISSUE TITLE
Mushrooms

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#38]
Some different 3D models with a bunch of mushrooms and not a single one per block for more difference.

Item texture
- [ ] red mushroom
- [x] brown mushroom

block model
- [ ] red mushroom
- [x] brown mushroom
- [ ] bloackstate

**Comment by MCAlagaesia** [comment]
So at this point in time we have one with a 3D model (the brown mushroom) and one as a 2D texture (red mushroom), so we should discuss which we should opt for.

I'm more on the side of using 2D textures. After all, that's what all the grass and flower blocks use, which would make finding a random 3D model on the ground seem out of place. The mushroom 3D models are also very intricate, which is in stark contrast with the rest of the blocky game.

**Comment by MCAlagaesia** [comment]
Here are the mushrooms in Faithful.

![2020-11-19_23 24 25](https://user-images.githubusercontent.com/10643460/99665942-67e2c600-2abe-11eb-841b-890b685b20d0.png)
