### ISSUE TITLE
Remove the modified end rod texture

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#42]
Since Minecraft 1.14, we now have proper lantern blocks.

The end rod should be restored to its original texture to allow it to be used in builds such as Ilia Feon.

**Comment by VoidShadow204** [comment]
Can I replace the new Lantern with this model, or should I keep the original one and just delete it?

**Comment by VoidShadow204** [comment]
I will remove the entire 3D model, as well as the texture and all relations in the next days, since this reduce the size of the pack and the new lantern fits the general style better.

**Comment by VoidShadow204** [comment]
I already removed those files a while ago. Just missed closing the issue.
