### ISSUE TITLE
New potion texture (the old are x16)

### ISSUE THREAD

**Issue by VoidShadow204** [MCAlagaesiaNetwork/Fairth#43]
Create some textures like bottles, cups etc. 

- [ ] Lingering Potion
- [ ] Splash Potion
- [x] Potion

**Comment by MCAlagaesia** [comment]
We should probably go back to bottles for potions. It better represents the wide range of fluids (whereas the tankards are only really for alcohol).

This is especially the case for water.

**Comment by VoidShadow204** [comment]
So we just remove anything from the Fairth and let Faithfull handle the work?

**Comment by MCAlagaesia** [comment]
Yeah, I think we can just remove these. In fact, they're an ancient texture from back when Hotline was doing some texturing, and they're still 16x16.
