### ISSUE TITLE
Remove unnecessary changes

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#47]
I have just documented the full list of changes that Fairth makes to the game in a89fe9dfabdfa231809abc3bd8eafa7762da2f92.

Some changes currently in the pack were not documented because I believe they should be removed. This issue is for discussing whether they should be removed or kept. They include:

- [x] Dark oak fences and gates - they have a new model that is different from the rest of the fences and gates in the game. The gate is not clearly visible in a fence. The change is unnecessary for the addon pack.
- [x] https://github.com/MCAlagaesiaNetwork/Fairth/blob/master/assets/minecraft/textures/shadow/flow_darkgrey.png (This file is not referenced in any part of the resource pack. What is it for? Good candidate for removal).

Should we decide to keep any of these changes, they need to be added to the list.

**Comment by VoidShadow204** [comment]
Have removed the files from
- dark oak fence
- invisible item frame
and the texture. It was remaining from the End-rod-lantern.
