### ISSUE TITLE
End rod retexture

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#5]
The vanilla end rod texture is unsuitable for the medieval setting in MCAlagaesia. It needs some "unspecified" tweaks.

**Comment by VoidShadow204** [comment]
Created a 3D modell for it. Also connecting to fences

**Comment by VoidShadow204** [comment]
Everyone loves the new Lantern, so i think its done

**Comment by VoidShadow204** [comment]
fixed some proplems with the 3D-Model
