### ISSUE TITLE
Blood

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#6]
**Replaces:** Redstone Dust
**Background Information:** Redstone dust is often used to show dried bloodstains on the ground in MCAlagaesia.

Any instances where Redstone is used for its original vanilla purpose are hidden.

**Comment by VoidShadow204** [comment]
Done. With an unpowered restone dot you get dark blood and with power, it gets light

**Comment by MCAlagaesia** [comment]
Looks good! Colours and shading look good when powered. Perhaps we can remove the powered redstone particle effect in the client so the blood doesn't have magical flying splatters.
