### ISSUE TITLE
Rotten Tomato

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#7]
**Replaces:** Snowball
**Background Information:** Rotten tomatoes retain the mechanics of vanilla snowballs. Or perhaps we could make it so that they do some small amount of damage. Either way, they are used to throw at people you don't like.

**Comment by PokeTehDoge** [comment]
Hey @MCAlagaesia! Would this work?
https://imgur.com/a/L6dqnEg
