### ISSUE TITLE
Flowering Azalea Leaves Have Black Flower Models

### ISSUE THREAD

**Issue by MCAlagaesia** [MCAlagaesiaNetwork/Fairth#90]
As seen in the image below, flowering azalea leaves have a black flower model.

Steps to reproduce:

- Enable Fairth v 0.16.0
- Place a flowering azalea leaves block

![2021-10-26_23 24 27](https://user-images.githubusercontent.com/10643460/138879016-8127bc3e-7e7c-438e-b35b-d5e682443aed.png)

**Comment by Sjmarf** [comment]
I intend to replace the Azalea Leaves texture with one more similar to that of the Oak, Spruce and Birch Leaves. For this reason, I'm not going to bother fixing it and rather replace the entire model at a later date 👍

**Comment by MCAlagaesia** [comment]
The old leaves were removed in 0.17.2, so I'll close this issue.
